language: elixir
elixir:
  - 1.3
  - 1.4
otp_release:
  - 18.3
  - 19.3

script:
  - "MIX_ENV=test mix do compile, coveralls.json --umbrella"

after_success:
  - bash <(curl -s https://codecov.io/bash)
